### PR TITLE
Caption scripts

### PR DESCRIPTION
**Pull request by calym**
Creates scripts for generating captions and new captions from published files on Amara

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Here are some of my comments @tnordberg :
1. The solution text for s3_q1 (the electrode one) is missing.
2. /captions/s1_i1_audio_en.vtt is missing.
3. /media/s1_i5_image.png is missing.
4. I couldn't find the captions for for `Quiz Intro` and `Final Score` screens.
5. There were separate Quiz intro and Final score videos, however, we discussed before that there would only be one. Is that correct? Do we need to change it to separate videos for each quiz?
6. There was an `Attract` screen video in the folder as well. Do we need to use that instead of the design we are currently using?

**Comment by tnordberg** [comment]
Thanks for bringing these missing pieces to our attention @abdulrauf11. See my comments below!

```
The solution text for s3_q1 (the electrode one) is missing.
/media/s1_i5_image.png is missing.
```
We have update these files in the Drive folder, so you should have them now.

`/captions/s1_i1_audio_en.vtt is missing.`
I will push this missing caption shortly.

`I couldn't find the captions for for Quiz Intro and Final Score screens.`
We'll go forward without these for the time-being. We'll have them ready for you before the next round of visitor-testing.

`There were separate Quiz intro and Final score videos, however, we discussed before that there would only be one. Is that correct? Do we need to change it to separate videos for each quiz?`
No, you can ignore the extra duplicate files. Each question-set will use the same intro/score media files. You can choose one of the files to use across all question-sets.

`There was an Attract screen video in the folder as well. Do we need to use that instead of the design we are currently using?`
Yes, but it doesn't replace the design. It will be a looping background video under your html text (https://d.pr/i/o4Aqpw). We caused confusion because our `attract_video.mp4` should not have any text in it. We are swapping in a plain background video for you shortly. We will eventually replace this with a video that contains the gradient plus additional video content fading in and out.

Thank you! Let us know if you find anything else that is blocking you.

**Comment by tnordberg** [comment]
@abdulrauf11 just following up: 
The `attract_video.mp4` should now be replaced.
I've pushed the missing `vtt` file to this branch.

**Comment by abdulrauf11** [comment]
@tnordberg I updated everything. You can review it now.

**Pull request merged**
