### PR TITLE
Milestone 6: Added Sound Effects + Code cleanup

### LINKED ISSUE #12: Intro video appearing in front of title
Background intro video should appear fullscreen, but _behind_ intro title panel.

https://d.pr/i/3bijNf

### LINKED ISSUE #18: Fix “cocnuts” typo
Small mistake by us, but you could you fix this typo: 

Search for the word `cocnuts` in the English text and change to `coconuts`.

### LINKED ISSUE #20: The correct answer sound should chime if even one player gets the correct answer.
The correct answer sound should chime if even one player gets the correct answer -- right now the wrong answer sound plays even when some players have answered correctly and the correct answer sound is only heard if all three players answer correctly.

### PR DESCRIPTION
**Pull request by abdulrauf11**
This PR includes the sound effects used throughout the app, as well as some code cleanup and optimization.

The sound effects can be updated through the `config.json` file:

```
"soundEffect": {
    "success": "/sound-effects/success.wav",
    "fail": "/sound-effects/fail.wav",
    "finalScore": "/sound-effects/final score.wav",
    "input": "/sound-effects/input.wav",
    "wait": "/sound-effects/wait.wav"
}
```

## Assets
All the images were optimized and resized to the appropriate size i.e. 1900 x 1200

## Types of Sound Effects
- **Success**: plays when all the players have answered correctly
- **Fail**: plays when any one of the players has answered incorrectly
- **Input**: plays when a player submits their answer
- **Wait**: plays (in a loop) while all the players are submitting their answers
- **Final Score**: plays when the players finish the quiz

## Test Link
https://tsck-bionic-eyes-quiz-show.netlify.app/

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Hey, @tnordberg you were ignoring media files in `.gitignore`:

```
# media files
*.m4v
*.mp4
*.mp3
*.wav
*.ogg
```
Let me know if this was intentional as I have commented it for now.

**Comment by abdulrauf11** [comment]
The reason some of the captions may not be working is that they are not included in the captions directory. Adding them to the folder will fix the issue automatically.

**Comment by tnordberg** [comment]
Hi @abdulrauf11, thanks for the update. 

The `.gitignore` excluding media files is intentional. We want to avoid pushing large media files to the repo if possible. 

Ideally, these media files should live in the Drive folder (https://bit.ly/3jU819s) and you manually add them to the project during development and before deploying a preview link. 

Is that possible with your current preview workflow, or is it automated in a way that everything needs to be included in the repo?

It's been very helpful having you provide preview links, but if necessary we could handle setting those up for the remainder of the project.

Otherwise, the sound effects are looking/sounding great. Sara is still distilling feedback from last week and we'll provide that as soon as possible.  

Thanks!

**Comment by abdulrauf11** [comment]
> Hi @abdulrauf11, thanks for the update.
> 
> The `.gitignore` excluding media files is intentional. We want to avoid pushing large media files to the repo if possible.
> 
> Ideally, these media files should live in the Drive folder (https://bit.ly/3jU819s) and you manually add them to the project during development and before deploying a preview link.
> 
> Is that possible with your current preview workflow, or is it automated in a way that everything needs to be included in the repo?
> 
> It's been very helpful having you provide preview links, but if necessary we could handle setting those up for the remainder of the project.
> 
> Otherwise, the sound effects are looking/sounding great. Sara is still distilling feedback from last week and we'll provide that as soon as possible.
> 
> Thanks!

Hey @tnordberg, it is necessary to include all the media files that are being referenced in the `content` files for the preview link to work.

Let's come back to this after we've fixed all the issues.

**Review by tnordberg — APPROVED** [review]
Looks good!

**Pull request merged**
