### PR TITLE
Milestone 1 - Data Structure

### PR DESCRIPTION
**Pull request by abdulrauf11**
The PR contains the design structure design for the quiz show app. External JSON file(s) are loaded into the application that allows for the configuration of all quiz content.

## Tasks
- Updated `node-sass` version as the previous version was not working on my system.
- Added two libraries: `stylelint-config-prettier` and `eslint-config-prettier` to avoid unnecessary conflicts between eslint and prettier.
- Content sourcing from external JSON files. These files can be found inside the `/content` directory.

## Test Link
This [link](https://tsck-bionic-eyes-quiz-show.netlify.app/) will allow you to view the JSON files being loaded in the application.

## Preview
Screenshot 2021-07-19 at 10 14 06 PM

## Questions for SMM
1. Can you mention all the different types of sound effects (_not the audio narration files_) that will be used throughout the site?
2. Do you think there's any content/config missing from the JSON files and should be added? (_Note: We will probably make further updates to the content files when we're building out components_)
3.  We've separated the content files based on all the screens. Do you prefer this or using just a single content file?
4. **For the next phase**:  Is it possible to change a few libraries that we used in the last project? We'd like to use `react-i18n` instead of `react-intl`. The reason we're thinking about the switch is better documentation of the react-i18n library, which makes it easier for the team to collaborate. Since our use-case isn't that complicated, it will be totally fine to stick with the same set of libraries as well.

### CODE REVIEW

**Comment by tnordberg** [comment]
Thank you!

We've already discussed many of the questions above in Chat, but I have a few suggestions regarding the Quiz data structure. I am thinking about what would be the most intuitive to a non-programmer content editor, so let me know if these would cause any issues for you. 

1. Since this will need to accommodate multiple "Question Sets," could the top level be an array of "Question Sets?"
2. Would it be possible to break out the language differences at a lower level? It is nice for content editors to see the various languages near each other for comparison. Currently, you would have to go find the corresponding question by matching index, which could become confusing as the Quiz grows.
3. Could question `type` become a descriptive string instead of a number? Strings are less flexibly programmatically, but will be more helpful to content editors. For example, these three key strings could work: `true-false`,  `multi-choice-text`,`multi-choice-media`.

Here's a stripped down example of what this might look like:

Screen Shot 2021-07-19 at 5 13 27 PM
(Tree view)
Screen Shot 2021-07-19 at 5 06 24 PM

**Comment by abdulrauf11** [comment]
2. @tnordberg  This is the default structure accepted by all the i18n libraries. It is much cleaner when it comes to using nested fields.
We can create a structure like the one you've suggested by writing a custom component that does dictionary lookups. Since our use-case is simple (no routing etc), we can use that as well. Just letting you know before I start working on this.


EDIT: Can you confirm if all the other fields (especially on the quiz page) will work for the team?

**Comment by abdulrauf11** [comment]
This how the new quiz JSON structure will look like. The following example has only 1 question in the quiz.

```json
{
    "questionSets": [
        [
            {
                "questionIntro": {
                    "title": {
                        "en": "Question 1",
                        "ar": "سؤال واحد"
                    },
                    "audio": {
                        "en": "/path/to/audio/narration/file-en",
                        "ar": "/path/to/audio/narration/file-ar"
                    },
                    "captions": {
                        "en": "/path/to/captions/file-en",
                        "ar": "/path/to/captions/file-ar"
                    }
                },
                
                "question": {
                    "type": "multiple-choice-media",
                    "text": {
                        "en": "Which image best represents the earliest bionic vision?",
                        "ar": "؟ﺔﻴﻟوأ ﺔﻴﻧوﺮﺘﻜﻟإ ﺔﻳؤر ﻞﻀﻓأ ﻞﺜﻤﺗ ﻲﺘﻟا ةرﻮﺼﻟا ﺎﻣ"
                    },
                    "audio": {
                        "en": "/path/to/audio/narration/file-en",
                        "ar": "/path/to/audio/narration/file-ar"
                    },
                    "options": [
                        {
                            "en": "1",
                            "ar": "1"
                        },
                        {
                            "en": "2",
                            "ar": "2"
                        },
                        {
                            "en": "3",
                            "ar": "3"
                        }
                    ],
                    "visualMedia": {
                        "image": "",
                        "video": "",
                        "images": [
                            "/path/to/option/image/1",
                            "/path/to/option/image/2",
                            "/path/to/option/image/3"
                        ]
                    }
                },
                
                "solution": {
                    "correctOptionIndex": 0,
                    "text": {
                        "en": "Researchers predict that within a few years, bionic eyes will produce vision as good as this image. In the decades to come, artificial vision may surpass natural vision in power and clarity.",
                        "ar": "يتوقع الباحثون أنه في غضون بضع سنوات ، ستنتج العيون الإلكترونية رؤية جيدة مثل هذه الصورة. في العقود القادمة ، قد تتجاوز الرؤية الاصطناعية الرؤية الطبيعية في القوة والوضوح."
                    },
                    "audio": {
                        "en": "/path/to/audio/narration/file-en",
                        "ar": "/path/to/audio/narration/file-ar"
                    }
                }
            }
        ]
    ]
}
```

**Comment by tnordberg** [comment]
@abdulrauf11 thanks for the background on your thinking. Please do use your first `ar`/`en` structure.  If this is an `i18n` standard, our content developers can learn to work with it.

Everything else looks good. Approving 👍

**Pull request merged**
